'use strict';

angular.module('euroProno2016WebApp', [
        'euroProno2016WebApp.auth',
        'euroProno2016WebApp.admin',
        'euroProno2016WebApp.constants',
        'euroProno2016WebApp.teams',
        'euroProno2016WebApp.matchs',
        'ngCookies',
        'ngResource',
        'ngSanitize',
        'btford.socket-io',
        'ui.router',
        'ui.bootstrap',
        'validation.match',
        'angular.filter',
        'pascalprecht.translate'
    ])
    .config(function($urlRouterProvider, $locationProvider, $translateProvider) {
        $urlRouterProvider
            .otherwise('/');

        $locationProvider.html5Mode(true);

        $translateProvider.translations('fr', {

            'For each match, prognotic the score and choose wich team will go in finale phase.': 'Pour chaque match, pronostiquez le score et choisissez quelle équipe ira en finale.',
            'Teams ranking are automatically updated as soon as your enter your score.': 'Les classements sont réalisés automatiquement dès que vous saisissez le score.',

            'sort by Name': 'Trier par nom',
            'sort by Group': 'Trier par groupe',
            'Group': 'Groupe',
            'Ranking': 'Rang',
            'BUTTON_LANG_EN': 'english',
            'BUTTON_LANG_FR': 'french',
            //Pays
            'Albania': 'Albanie',
            'Austria': 'Autriche',
            'Belgium': 'Belgique',
            'Croatia': 'Croatie',
            'Czech Republic': 'République Tchèque',
            'England': 'Angleterre',
            'Germany': 'Allemagne',
            'Hungary': 'Hongrie',
            'Iceland': 'Islande',
            'Italy': 'Italie',
            'Northern Irland': 'Irlande du nord',
            'Republic of Irland': 'République d Irlande',
            'Spain': 'Espagne',
            'Wales': 'Pays de Galles',
            'Romania': 'Roumanie',
            'Russia': 'Russie',
            'Slovakia': 'Slovaquie',
            'Sweden': 'Suède',
            'Switzerland': 'Suisse',
            'Turkey': 'Turquie',
            'Poland': 'Pologne',
            'Day 1': 'Jour 1',
            'Day 2': 'Jour 2',
            'Day 3': 'Jour 3',
            'Round of 16': '8 eme',
            'Quarter Finals': 'Quart de finale',
            'Semi Final': 'Demi finale',
            'Small final': 'Petite finale',
            'Stadium': 'Stade',
            'Teams': 'Equipes',
            'Final': 'Finale',
            'Runner-up A': 'Second A',
            'Runner-up B': 'Second B',
            'Runner-up C': 'Second C',
            'Runner-up D': 'Second D',
            'Runner-up E': 'Second E',
            'Runner-up F': 'Second F',
            'Winner A': 'Vainqueur A',
            'Winner B': 'Vainqueur B',
            'Winner C': 'Vainqueur C',
            'Winner D': 'Vainqueur D',
            'Winner E': 'Vainqueur E',
            'Winner F': 'Vainqueur F',
            'Third-place A/C/D': 'Troisième A/C/D',
            'Third-place B/E/F': 'Troisième B/E/F',
            'Third-place C/D/E': 'Troisième C/D/E',
            'Third-place A/B/F': 'Troisième A/B/F'
        });


        $translateProvider.translations('es', {
            'For each match, prognotic the score and choose wich team will go in finale phase.': 'Para cada partido, prognotic la partitura y elegir a un equipo wich irá en la fase final.',
            'Teams ranking are automatically updated as soon as your enter your score.': 'Equipos de la clasificación se actualizan automáticamente tan pronto como su escriba su puntuación.',

            'sort by Name': 'Ordenar por nombre',
            'sort by Group': 'ordenar por Grupo',
            'Group': 'Grupo',
            'Ranking': 'Grupo',
            'BUTTON_LANG_EN': 'english',
            'BUTTON_LANG_FR': 'french',
            //Pays
            'France': 'Francia',
            'Belgium': 'Bélgica',
            'Croatia': 'Croacia',
            'Czech Republic': 'República Checa',
            'England': 'Inglaterra',
            'Germany': 'Alemania',
            'Hungary': 'Hungria',
            'Iceland': 'Islandia',
            'Italy': 'Italia',
            'Northern Ireland': 'Irlanda del Norte',
            'Republic of Irland': 'República de Irlanda',
            'Spain': 'España',
            'Ukraine': 'Ucrania',
            'Wales': 'Gales',
            'Romania': 'Rumania',
            'Russia': 'Rusia',
            'Slovakia': 'Eslovaquia',
            'Sweden': 'Suecia',
            'Switzerland': 'Suiza',
            'Turkey': 'Turquia',
            'Poland': 'Polonia',
            'Day 1': 'Jordana 1',
            'Day 2': 'Jordana 2',
            'Day 3': 'Jordana 3',
            'Round of 16': 'Octavos de Final',
            'Quarter Finals': 'Cuartos de finaL',
            'Semi Final': 'Semifinal',
            'Small final': 'Pequeño final',
            'Stadium': 'Estadio',
            'Teams': 'Equipos',
            'Runner-up A': 'Segundo A',
            'Runner-up B': 'Segundo B',
            'Runner-up C': 'Segundo C',
            'Runner-up D': 'Segundo D',
            'Runner-up E': 'Segundo E',
            'Runner-up F': 'Segundo F',
            'Winner A': 'Ganador A',
            'Winner B': 'Ganador B',
            'Winner C': 'Ganador C',
            'Winner D': 'Ganador D',
            'Winner E': 'Ganador E',
            'Winner F': 'Ganador F',
            'Third-place A/C/D': 'Tercero A/C/D',
            'Third-place B/E/F': 'Tercero B/E/F',
            'Third-place C/D/E': 'Tercero C/D/E',
            'Third-place A/B/F': 'Tercero A/B/F'
        });

        $translateProvider.translations('de', {
            'For each match, prognotic the score and choose wich team will go in finale phase.': 'Für jedes Spiel prognotic die Partitur und wählen Sie wich Team in Finale Phase gehen.',
            'Teams ranking are automatically updated as soon as your enter your score.': 'Teams Ranking werden , sobald Ihr geben Sie Ihre Punktzahl automatisch aktualisiert',

            'sort by Name': 'Nach Name sortieren',
            'sort by Group': 'sortieren nach Gruppe',
            'Group': 'Gruppe',
            'Ranking': 'Rang',
            'BUTTON_LANG_EN': 'english',
            'BUTTON_LANG_FR': 'french',
            //Pays
            'Albania': 'Albanien',
            'France': 'Frankreich',
            'Austria': 'Österreich',
            'Belgium': 'Belgien',
            'Croatia': 'Kroatien',
            'Czech Republic': 'Tschechische Rep',
            'Northern Ireland': 'Nordirland',
            'Germany': 'Deutschland',
            'Hungary': 'Ungarn',
            'Iceland': 'Island',
            'Italy': 'Italien',
            'Republic of Irland': 'Republik Irland',
            'Spain': 'Spanien',
            'Romania': 'Rumänien',
            'Russia': 'Russland',
            'Slovakia': 'Slowakei',
            'Sweden': 'Schweden',
            'Switzerland': 'Schweiz',
            'Turkey': 'Turkei',
            'Poland': 'Polen',
            'Day 1': 'Spieltag 1',
            'Day 2': 'Spieltag 2',
            'Day 3': 'Spieltag 3',
            'Round of 16': 'Achtelfinals',
            'Quarter Finals': 'Viertelfinale',
            'Semi Final': 'Halbfinale',
            'Small final': ' Kleines Finale',
            'Stadium': 'Fußballstadion',
            'Final': 'Endspiel',
            'Runner-up A': 'Zweite A',
            'Runner-up B': 'Zweite B',
            'Runner-up C': 'Zweite C',
            'Runner-up D': 'Zweite D',
            'Runner-up E': 'Zweite E',
            'Runner-up F': 'Zweite F',
            'Winner A': 'Sieger A',
            'Winner B': 'Sieger B',
            'Winner C': 'Sieger C',
            'Winner D': 'Sieger D',
            'Winner E': 'Sieger E',
            'Winner F': 'Sieger F',
            'Third-place A/C/D': 'Dritter Platz A/C/D',
            'Third-place B/E/F': 'Dritter B/E/F',
            'Third-place C/D/E': 'Dritter C/D/E',
            'Third-place A/B/F': 'Dritter A/B/F'

        });

        $translateProvider.preferredLanguage('en');

    });
